#!/bin/sh

export BASEDIR=$(dirname $0)
export system64=$(uname -m)
export OS=$(uname -s)

cd $BASEDIR

if test "$OS" = "Linux"
then
    chmod 755 ./x10flasher_lib/adb.linux
    chmod 755 ./x10flasher_lib/fastboot.linux
    chmod 755 ./x10flasher_lib/unyaffs.linux
    chmod 755 ./x10flasher_lib/bin2elf
    chmod 755 ./x10flasher_lib/bin2sin
    if [ "$(whoami)" != "root" ]
    then
	export HASRULES="false"
	if test -d /etc/udev/rules.d
	then
        	if grep -rl "0fce" /etc/udev/rules.d >/dev/null
        	then
			export HASRULES="true"
		fi
	fi
	if test -d /lib/udev/rules.d
	then
        	if grep -rl "0fce" /lib/udev/rules.d >/dev/null
        	then
			export HASRULES="true"
		fi
	fi
	if test "$HASRULES" = "true"
	then
    		echo "Not running as root but Sony/SonyEriccson Vendor ID found on your udev rules"
       		echo "if Flashing didn't work well, run flashtool as root"
       	else
       		echo "Not running as root and there is no Sony/SonyEriccson Vendor ID on your udev rules"   
       		echo "The user must be granted access to adb/flashmode/fastboot"
       		echo "If you are unsure what to do, run flashtool as root"
       		exit 1
       	fi
    else
        echo "Running as root."
    fi
    if test -z "${JAVA_HOME}"
    then
        if test "${system64}" = "x86_64"
        then
             export JAVA_HOME=./x10flasher_lib/linjre64
        else
             export JAVA_HOME=./x10flasher_lib/linjre32
        fi
        echo "JAVA_HOME not set. Using default value : ${JAVA_HOME}"
    fi
    if test -e ${JAVA_HOME}/bin/java
    then
         if test "${system64}" = "x86_64"
         then
             export LD_LIBRARY_PATH=./x10flasher_lib/linux/lib64:$LD_LIBRARY_PATH
             ln -sf libusb-1.0.so.0.1.0 ./x10flasher_lib/linux/lib64/libusb-1.0.so
         else
             export LD_LIBRARY_PATH=./x10flasher_lib/linux/lib32:$LD_LIBRARY_PATH
             ln -sf libusb-1.0.so.0.1.0 ./x10flasher_lib/linux/lib32/libusb-1.0.so
         fi
         $JAVA_HOME/bin/java -Xms128m -Xmx512m -Duser.country=US -Duser.language=en -jar x10flasher.jar
    else
         echo "No Java in specified path in JAVA_HOME=${JAVA_HOME}"
         echo "Set the variable to a valid Java installation"
    fi
else
    chmod 755 ./x10flasher_lib/adb.mac
    chmod 755 ./x10flasher_lib/fastboot.mac
    chmod 755 ./x10flasher_lib/unyaffs.mac
    export DYLD_LIBRARY_PATH=./x10flasher_lib/mac/lib64:$DYLD_LIBRARY_PATH
    export DYLD_LIBRARY_PATH=./x10flasher_lib/mac/lib32:$DYLD_LIBRARY_PATH
    ln -sf libusb-1.0.0.dylib ./x10flasher_lib/mac/lib64/libusb-1.0.dylib
    ln -sf libusb-1.0.0.dylib ./x10flasher_lib/mac/lib32/libusb-1.0.dylib
    java -Xms128m -Xmx512m -Duser.country=US -Duser.language=en -jar x10flasher.jar
fi
