#!/bin/sh

export BASEDIR=$(dirname $0)
export system64=$(uname -a|grep x86_64|wc -l)

if test -z "${JAVA_HOME}"
then
	if test "${system64}" = "0"
	then
		export JAVA_HOME=${BASEDIR}/x10flasher_lib/linjre32
	else
		export JAVA_HOME=${BASEDIR}/x10flasher_lib/linjre64
	fi
	echo "JAVA_HOME not set. Using default value : ${JAVA_HOME}"
fi

chmod 755 ${BASEDIR}/x10flasher_lib/adb.linux
chmod 755 ${BASEDIR}/x10flasher_lib/fastboot.linux
chmod 755 ${BASEDIR}/x10flasher_lib/adb.mac
chmod 755 ${BASEDIR}/x10flasher_lib/fastboot.mac

if test -e ${JAVA_HOME}/bin/java
then
	$JAVA_HOME/bin/java -Xms128m -Xmx512m -jar x10flasher.jar
else
	echo "No Java in specified path in JAVA_HOME=${JAVA_HOME}"
	echo "Set the variable to a valid Java installation"
fi
